export const ERROR_MESSAGE = {
  descriptionBlank: 'Message may not be blank',
  descriptionLength: 'Message must be between 20 and 2000 characters.',
  emailBlank: 'Email may not be blank',
  emailWrongFormat: 'must be a well-formed email address',
  phoneLength: 'Phone must be between 11 and 21 characters.',
  phoneSpecialCharacter: 'Phone may not contain special characters',
  phoneBlank: 'Phone may not be blank',
  phoneSet: 'Phone must be set',
  subjectLength: 'Subject must be between 5 and 100 characters.',
  subjectBlank: 'Subject may not be blank',
  nameBlank: 'Name may not be blank',
  nameNumbers: 'Name may not contain numbers',
  nameSpecialCharacter: 'Name may not contain special characters',
  nameSet: 'Name must be set',
  emailSet: 'Email must be set',
  subjectSet: 'Subject must be set',
  descriptionSet: 'Message must be set',
};
